name = "catalyst-workbook"
compatibility_date = "2025-11-04"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "catalyst-production"
database_id = "ffb6472b-3510-452d-adcb-5b1a06e033a7"
